MQTT: 
  IP: "192.168.20.249"
  Port: 1883
  KeepAlive: 60
  User: ""
  Password: ""
  rootPath: "WIATA"
Device:
  IP: "192.168.20.120"
  Port: 4002
  SlaveAddress: 1
  Name: "ISA010"
Settings:
  ScanRate: 5
